apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: curl-public-ok
  namespace: npd
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: curl-public-ok
  policyTypes:
    - Ingress
    - Egress
